apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-service
spec:
  replicas: {{ .Values.templateService.replicas }}
  selector:
    matchLabels:
      app: template-service
  template:
    metadata:
      labels:
        app: template-service
    spec:
      containers:
      - name: template-service
        image: {{ .Values.templateService.image }}
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.templateService.port }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ACTIVE_PROFILES
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: db-secret
