server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/sbt?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
    open-in-view: false
    defer-datasource-initialization: false