apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ "root" | b64enc }}
  MYSQL_HOST: {{ "mysql" | b64enc }}
  MYSQL_PORT: {{ "3306" | b64enc }}
  MYSQL_DATABASE: {{ "sbt" | b64enc }}