apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: {{ .Values.userService.replicas }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: {{ .Values.userService.image }}
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.userService.port }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ACTIVE_PROFILES
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: db-secret
